"""widen_ai_trace_prompt_version_column

Revision ID: 439125ea9954
Revises: eee73acb6941
Create Date: 2026-08-26 22:22:25.560555

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '439125ea9954'
down_revision: str | None = 'eee73acb6941'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_traces', 'prompt_version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_traces', 'prompt_version',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
