"""add_gmail_ingestion

Revision ID: 45d9ec03da61
Revises: d93721f82c21
Create Date: 2026-08-27 14:01:17.648134

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '45d9ec03da61'
down_revision: str | None = 'd93721f82c21'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_credentials',
    sa.Column('connected_email', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmail_credentials'))
    )
    op.create_table('processed_gmail_messages',
    sa.Column('gmail_message_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('jobs_extracted', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_gmail_messages'))
    )
    op.create_index(op.f('ix_processed_gmail_messages_gmail_message_id'), 'processed_gmail_messages', ['gmail_message_id'], unique=True)
    op.add_column(
        'app_settings',
        sa.Column(
            'gmail_sync_frequency_minutes',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('30'),
        ),
    )
    op.add_column('app_settings', sa.Column('next_gmail_sync_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'next_gmail_sync_at')
    op.drop_column('app_settings', 'gmail_sync_frequency_minutes')
    op.drop_index(op.f('ix_processed_gmail_messages_gmail_message_id'), table_name='processed_gmail_messages')
    op.drop_table('processed_gmail_messages')
    op.drop_table('gmail_credentials')
    # ### end Alembic commands ###
