"""milestone 2: discovery, search profiles, application status, cv fields

Revision ID: 765f77f370b8
Revises: 8094a61c953b
Create Date: 2026-08-26 15:17:41.901172

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '765f77f370b8'
down_revision: str | None = '8094a61c953b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('auto_ai_analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_ai_analyses_per_run', sa.Integer(), nullable=False),
    sa.Column('daily_ai_analysis_budget_usd', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('discovery_runs',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('search_profile_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('sources_used', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('retrieved_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('prefilter_rejected_count', sa.Integer(), nullable=False),
    sa.Column('eligible_count', sa.Integer(), nullable=False),
    sa.Column('analysed_count', sa.Integer(), nullable=False),
    sa.Column('deferred_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('strong_apply_or_better_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_runs'))
    )
    op.create_table('search_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('locations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('include_remote', sa.Boolean(), nullable=False),
    sa.Column('max_experience_level', sa.String(length=50), nullable=True),
    sa.Column('excluded_keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_profiles'))
    )
    op.create_table('application_status_events',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_application_status_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_status_events'))
    )
    op.create_table('certifications',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('issuer', sa.String(length=300), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_certifications_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_table('discovered_jobs',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('remote_type', sa.String(length=20), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('description_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prefilter_reason', sa.Text(), nullable=True),
    sa.Column('search_profile_id', sa.UUID(), nullable=True),
    sa.Column('discovery_run_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], name=op.f('fk_discovered_jobs_discovery_run_id_discovery_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_discovered_jobs_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], name=op.f('fk_discovered_jobs_search_profile_id_search_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_jobs')),
    sa.UniqueConstraint('job_id', name=op.f('uq_discovered_jobs_job_id'))
    )
    op.create_index(op.f('ix_discovered_jobs_dedupe_fingerprint'), 'discovered_jobs', ['dedupe_fingerprint'], unique=False)
    op.create_index(op.f('ix_discovered_jobs_description_fingerprint'), 'discovered_jobs', ['description_fingerprint'], unique=False)
    op.create_index(op.f('ix_discovered_jobs_external_id'), 'discovered_jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_discovered_jobs_status'), 'discovered_jobs', ['status'], unique=False)
    # server_default backfills the existing (seeded) candidate row - adding a
    # NOT NULL array column with no default would fail against a non-empty
    # table. The Python-side `default=list` on the ORM column only applies
    # to new INSERTs, so it doesn't help existing rows here.
    op.add_column(
        'candidates',
        sa.Column(
            'preferred_technologies',
            sa.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column(
        'candidates',
        sa.Column(
            'excluded_job_types',
            sa.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column('jobs', sa.Column('application_status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'application_status')
    op.drop_column('candidates', 'excluded_job_types')
    op.drop_column('candidates', 'preferred_technologies')
    op.drop_index(op.f('ix_discovered_jobs_status'), table_name='discovered_jobs')
    op.drop_index(op.f('ix_discovered_jobs_external_id'), table_name='discovered_jobs')
    op.drop_index(op.f('ix_discovered_jobs_description_fingerprint'), table_name='discovered_jobs')
    op.drop_index(op.f('ix_discovered_jobs_dedupe_fingerprint'), table_name='discovered_jobs')
    op.drop_table('discovered_jobs')
    op.drop_table('certifications')
    op.drop_table('application_status_events')
    op.drop_table('search_profiles')
    op.drop_table('discovery_runs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
