"""initial schema

Revision ID: 8094a61c953b
Revises: 
Create Date: 2026-08-26 14:16:56.159269

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '8094a61c953b'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # Required for the evidence.embedding column (unused by V1 deterministic
    # matching, reserved for future semantic retrieval - see
    # app/db/models/candidate.py).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_traces',
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_identifier', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_traces'))
    )
    op.create_table('candidates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('preferred_job_categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('preferred_locations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('work_rights', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('salary_expectation_min', sa.Integer(), nullable=True),
    sa.Column('salary_expectation_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=False),
    sa.Column('remote_preference', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_table('jobs',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('achievements',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_achievements_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    op.create_table('educations',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=300), nullable=False),
    sa.Column('qualification', sa.String(length=300), nullable=False),
    sa.Column('field_of_study', sa.String(length=300), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_educations_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_educations'))
    )
    op.create_table('evidence',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_label', sa.String(length=300), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('skill_tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_evidence_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_table('job_analyses',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('extracted_job', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fit_score', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_analyses_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_analyses'))
    )
    op.create_table('projects',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technologies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('highlights', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_projects_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('skills',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('proficiency', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_skills_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_table('work_experiences',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('technologies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_work_experiences_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_experiences'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experiences')
    op.drop_table('skills')
    op.drop_table('projects')
    op.drop_table('job_analyses')
    op.drop_table('evidence')
    op.drop_table('educations')
    op.drop_table('achievements')
    op.drop_table('jobs')
    op.drop_table('candidates')
    op.drop_table('ai_traces')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
