"""milestone 3: watchlist, source observations, health, attention, scheduling

Revision ID: 8c385d11b4e6
Revises: 765f77f370b8
Create Date: 2026-08-26 16:05:40.892696

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8c385d11b4e6'
down_revision: str | None = '765f77f370b8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_watchlist',
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('careers_url', sa.String(length=1000), nullable=True),
    sa.Column('ats_type', sa.String(length=30), nullable=False),
    sa.Column('ats_identifier', sa.String(length=200), nullable=False),
    sa.Column('preferred_locations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_watchlist')),
    sa.UniqueConstraint('ats_type', 'ats_identifier', name='uq_company_watchlist_ats')
    )
    op.create_table('source_health',
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error_category', sa.String(length=200), nullable=True),
    sa.Column('jobs_retrieved_last_run', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_health'))
    )
    op.create_index(op.f('ix_source_health_source_key'), 'source_health', ['source_key'], unique=True)
    op.create_table('attention_items',
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_discovered_job_id', sa.UUID(), nullable=True),
    sa.Column('related_job_id', sa.UUID(), nullable=True),
    sa.Column('related_company', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_discovered_job_id'], ['discovered_jobs.id'], name=op.f('fk_attention_items_related_discovered_job_id_discovered_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_job_id'], ['jobs.id'], name=op.f('fk_attention_items_related_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attention_items'))
    )
    op.create_index('ix_attention_items_status', 'attention_items', ['status'], unique=False)
    op.create_table('source_observations',
    sa.Column('discovered_job_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('match_stage', sa.String(length=30), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('discovery_run_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['discovered_job_id'], ['discovered_jobs.id'], name=op.f('fk_source_observations_discovered_job_id_discovered_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], name=op.f('fk_source_observations_discovery_run_id_discovery_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_observations'))
    )
    op.create_index('ix_source_observations_discovered_job_id', 'source_observations', ['discovered_job_id'], unique=False)
    # server_default on these four - app_settings/discovery_runs/search_profiles
    # already have rows in any environment that's used the app at all, so a
    # plain NOT NULL ADD COLUMN with no default would fail (see the same
    # fix in the previous migration).
    op.add_column(
        'app_settings',
        sa.Column(
            'auto_discovery_enabled', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        'app_settings',
        sa.Column(
            'discovery_frequency_hours', sa.Integer(), nullable=False, server_default='24'
        ),
    )
    op.add_column(
        'app_settings',
        sa.Column(
            'max_postings_per_source_per_run', sa.Integer(), nullable=False, server_default='100'
        ),
    )
    op.add_column('app_settings', sa.Column('last_scheduled_run_at', sa.DateTime(), nullable=True))
    op.add_column('app_settings', sa.Column('next_scheduled_run_at', sa.DateTime(), nullable=True))
    op.add_column('discovered_jobs', sa.Column('analysis_priority', sa.Float(), nullable=True))
    op.add_column('discovered_jobs', sa.Column('latest_overall_score', sa.Float(), nullable=True))
    op.add_column('discovered_jobs', sa.Column('latest_recommendation', sa.String(length=50), nullable=True))
    op.add_column('discovered_jobs', sa.Column('latest_priority', sa.String(length=50), nullable=True))
    op.add_column('discovered_jobs', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_discovered_jobs_analysis_priority'), 'discovered_jobs', ['analysis_priority'], unique=False)
    op.create_index('ix_discovered_jobs_created_at', 'discovered_jobs', ['created_at'], unique=False)
    op.create_index('ix_discovered_jobs_status_score', 'discovered_jobs', ['status', 'latest_overall_score'], unique=False)
    op.add_column(
        'discovery_runs',
        sa.Column('triggered_by', sa.String(length=20), nullable=False, server_default='manual'),
    )
    op.add_column(
        'discovery_runs',
        sa.Column('ai_calls_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'discovery_runs',
        sa.Column('ai_input_tokens', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'discovery_runs',
        sa.Column('ai_output_tokens', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'search_profiles',
        sa.Column(
            'keyword_groups',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        'search_profiles',
        sa.Column(
            'location_priority',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_profiles', 'location_priority')
    op.drop_column('search_profiles', 'keyword_groups')
    op.drop_column('discovery_runs', 'ai_output_tokens')
    op.drop_column('discovery_runs', 'ai_input_tokens')
    op.drop_column('discovery_runs', 'ai_calls_count')
    op.drop_column('discovery_runs', 'triggered_by')
    op.drop_index('ix_discovered_jobs_status_score', table_name='discovered_jobs')
    op.drop_index('ix_discovered_jobs_created_at', table_name='discovered_jobs')
    op.drop_index(op.f('ix_discovered_jobs_analysis_priority'), table_name='discovered_jobs')
    op.drop_column('discovered_jobs', 'reviewed_at')
    op.drop_column('discovered_jobs', 'latest_priority')
    op.drop_column('discovered_jobs', 'latest_recommendation')
    op.drop_column('discovered_jobs', 'latest_overall_score')
    op.drop_column('discovered_jobs', 'analysis_priority')
    op.drop_column('app_settings', 'next_scheduled_run_at')
    op.drop_column('app_settings', 'last_scheduled_run_at')
    op.drop_column('app_settings', 'max_postings_per_source_per_run')
    op.drop_column('app_settings', 'discovery_frequency_hours')
    op.drop_column('app_settings', 'auto_discovery_enabled')
    op.drop_index('ix_source_observations_discovered_job_id', table_name='source_observations')
    op.drop_table('source_observations')
    op.drop_index('ix_attention_items_status', table_name='attention_items')
    op.drop_table('attention_items')
    op.drop_index(op.f('ix_source_health_source_key'), table_name='source_health')
    op.drop_table('source_health')
    op.drop_table('company_watchlist')
    # ### end Alembic commands ###
