"""add_geographic_eligibility_gate

Revision ID: d93721f82c21
Revises: 439125ea9954
Create Date: 2026-08-26 23:02:58.434054

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd93721f82c21'
down_revision: str | None = '439125ea9954'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovered_jobs', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column(
        'discovered_jobs',
        sa.Column(
            'geographic_eligibility',
            sa.String(length=30),
            nullable=False,
            # Existing rows (pre-dating this gate) default to
            # location_unconfirmed - excluded from the recommended feed
            # until the backfill script (scripts/backfill_location_eligibility.py)
            # classifies them properly, never silently treated as eligible.
            server_default=sa.text("'location_unconfirmed'"),
        ),
    )
    op.add_column('discovered_jobs', sa.Column('geographic_eligibility_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_discovered_jobs_geographic_eligibility'), 'discovered_jobs', ['geographic_eligibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_jobs_geographic_eligibility'), table_name='discovered_jobs')
    op.drop_column('discovered_jobs', 'geographic_eligibility_reason')
    op.drop_column('discovered_jobs', 'geographic_eligibility')
    op.drop_column('discovered_jobs', 'country')
    # ### end Alembic commands ###
