"""milestone_4a_application_intelligence

Revision ID: eee73acb6941
Revises: 8c385d11b4e6
Create Date: 2026-08-26 22:14:29.753751

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eee73acb6941'
down_revision: str | None = '8c385d11b4e6'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_styles',
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('avoid_buzzwords', sa.Boolean(), nullable=False),
    sa.Column('avoid_exaggerated_claims', sa.Boolean(), nullable=False),
    sa.Column('prefer_specific_examples', sa.Boolean(), nullable=False),
    sa.Column('avoid_em_dashes', sa.Boolean(), nullable=False),
    sa.Column('region_convention', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_styles'))
    )
    op.create_table('research_sources',
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('domain', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_quality', sa.String(length=20), nullable=False),
    sa.Column('fetch_status', sa.String(length=20), nullable=False),
    sa.Column('raw_text_excerpt', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources'))
    )
    op.create_index('ix_research_sources_company_name', 'research_sources', ['company_name'], unique=False)
    op.create_table('application_workspaces',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('research_company_name', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_application_workspaces_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_workspaces')),
    sa.UniqueConstraint('job_id', name=op.f('uq_application_workspaces_job_id'))
    )
    op.create_table('research_claims',
    sa.Column('research_source_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('supporting_excerpt', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['research_source_id'], ['research_sources.id'], name=op.f('fk_research_claims_research_source_id_research_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_claims'))
    )
    op.create_index('ix_research_claims_company_name', 'research_claims', ['company_name'], unique=False)
    op.create_table('application_question_responses',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('classifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answered_deterministically', sa.Boolean(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('source_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_research_claim_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('reviewer_result', sa.String(length=30), nullable=True),
    sa.Column('reviewer_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regeneration_attempt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['application_workspaces.id'], name=op.f('fk_application_question_responses_workspace_id_application_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_question_responses'))
    )
    op.create_index('ix_application_question_responses_workspace_key', 'application_question_responses', ['workspace_id', 'question_key'], unique=False)
    op.create_table('cover_letters',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_research_claim_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('reviewer_result', sa.String(length=30), nullable=True),
    sa.Column('reviewer_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regeneration_attempt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['application_workspaces.id'], name=op.f('fk_cover_letters_workspace_id_application_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cover_letters'))
    )
    op.create_index('ix_cover_letters_workspace_id', 'cover_letters', ['workspace_id'], unique=False)
    op.create_table('cv_tailoring_batches',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_emphasis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('reviewer_result', sa.String(length=30), nullable=True),
    sa.Column('reviewer_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regeneration_attempt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['application_workspaces.id'], name=op.f('fk_cv_tailoring_batches_workspace_id_application_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cv_tailoring_batches'))
    )
    op.create_index('ix_cv_tailoring_batches_workspace_id', 'cv_tailoring_batches', ['workspace_id'], unique=False)
    op.create_table('gap_analyses',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_analysis_id', sa.UUID(), nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gap_strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_analysis_id'], ['job_analyses.id'], name=op.f('fk_gap_analyses_job_analysis_id_job_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['application_workspaces.id'], name=op.f('fk_gap_analyses_workspace_id_application_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gap_analyses'))
    )
    op.create_table('application_strategies',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('gap_analysis_id', sa.UUID(), nullable=False),
    sa.Column('positioning', sa.Text(), nullable=False),
    sa.Column('lead_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills_to_emphasise', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills_to_deemphasise', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('likely_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('motivation_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('application_priority', sa.String(length=30), nullable=True),
    sa.Column('recommendation', sa.String(length=30), nullable=False),
    sa.Column('source_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_research_claim_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('reviewer_result', sa.String(length=30), nullable=True),
    sa.Column('reviewer_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regeneration_attempt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gap_analysis_id'], ['gap_analyses.id'], name=op.f('fk_application_strategies_gap_analysis_id_gap_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['application_workspaces.id'], name=op.f('fk_application_strategies_workspace_id_application_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_strategies'))
    )
    op.create_index('ix_application_strategies_workspace_id', 'application_strategies', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_application_strategies_workspace_id', table_name='application_strategies')
    op.drop_table('application_strategies')
    op.drop_table('gap_analyses')
    op.drop_index('ix_cv_tailoring_batches_workspace_id', table_name='cv_tailoring_batches')
    op.drop_table('cv_tailoring_batches')
    op.drop_index('ix_cover_letters_workspace_id', table_name='cover_letters')
    op.drop_table('cover_letters')
    op.drop_index('ix_application_question_responses_workspace_key', table_name='application_question_responses')
    op.drop_table('application_question_responses')
    op.drop_index('ix_research_claims_company_name', table_name='research_claims')
    op.drop_table('research_claims')
    op.drop_table('application_workspaces')
    op.drop_index('ix_research_sources_company_name', table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_table('communication_styles')
    # ### end Alembic commands ###
